// Code generated by hertz generator.

package main

import (
	"context"
	"log"
	"net/http"
	"strings"
	"time"

	"github.com/cloudwego/gomall/app/frontend/biz/router"
	"github.com/cloudwego/gomall/app/frontend/conf"
	"github.com/cloudwego/gomall/app/frontend/infra/rpc"
	"github.com/cloudwego/gomall/app/frontend/middleware"
	"github.com/cloudwego/gomall/common/mtl"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/logger/accesslog"
	hertzlogrus "github.com/hertz-contrib/logger/logrus"
	prometheus "github.com/hertz-contrib/monitor-prometheus"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/hertz-contrib/pprof"
	"github.com/hertz-contrib/sessions"
	"github.com/hertz-contrib/sessions/redis"
	oteltrace "go.opentelemetry.io/otel/trace"
	"go.uber.org/zap/zapcore"
	"gopkg.in/natefinch/lumberjack.v2"
)

var (
	ServiceName      = conf.GetConf().Hertz.Service
	RegisterAddr     = conf.GetConf().Registry.RegistryAddress[0]
	ConsulHealthAddr = conf.GetConf().Hertz.ConsulHealthAddr
	MetricsPort      = conf.GetConf().Hertz.MetricsPort
)

func main() {
	consul, registryInfo := mtl.InitMetric(ServiceName, MetricsPort, RegisterAddr)

	// hertz取消注册的方式
	defer consul.Deregister(registryInfo)

	// hertz-opentelemetry集成
	p := mtl.InitTracing(ServiceName)

	defer p.Shutdown(context.Background())

	rpc.Init()

	// opentelemetry
	tracer, cfg := hertztracing.NewServerTracer(
		hertztracing.WithCustomResponseHandler(func(c context.Context, ctx *app.RequestContext) {
			ctx.Header("shop-trace-id", oteltrace.SpanFromContext(c).SpanContext().TraceID().String())
		}),
	)

	address := conf.GetConf().Hertz.Address
	h := server.New(server.WithHostPorts(address),
		// 添加promethus中间件到Hertz
		server.WithTracer(prometheus.NewServerTracer(
			"",
			"",
			prometheus.WithDisableServer(true),
			prometheus.WithRegistry(mtl.Registry),
		)),
		// 添加opentelemetry
		tracer,
	)

	// opentelemetry
	h.Use(hertztracing.ServerMiddleware(cfg))

	registerMiddleware(h)

	// add a ping route to test
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})

	router.GeneratedRegister(h)

	h.LoadHTMLGlob("template/*")
	h.Static("/static", "./")

	// 为访问sign-in路径渲染新页面
	h.GET("/sign-in", func(c context.Context, ctx *app.RequestContext) {
		data := utils.H{
			"title": "Sign In",
			// 保留上一层页面路径并渲染给sign-in
			"next": ctx.Query("next"),
		}
		ctx.HTML(consts.StatusOK, "sign-in", data)
	})

	// 为访问sign-up渲染页面
	h.GET("/sign-up", func(c context.Context, ctx *app.RequestContext) {
		data := utils.H{
			"title": "Sign In",
		}
		ctx.HTML(consts.StatusOK, "sign-up", data)
	})

	h.GET("/about", func(c context.Context, ctx *app.RequestContext) {
		ctx.HTML(consts.StatusOK, "about", utils.H{"Title": "About"})
	})

	// 健康检查
	go StartHealthCheckServer(":" + strings.Split(ConsulHealthAddr, ":")[1])

	h.Spin()
}

func registerMiddleware(h *server.Hertz) {
	// 注册session redis组件到中间层
	store, err := redis.NewStore(10, "tcp", conf.GetConf().Redis.Address, conf.GetConf().Redis.Password, []byte("secret"))
	if err != nil {
		panic(err)
	}

	h.Use(sessions.New("cloudwego-shop", store))

	// log
	logger := hertzlogrus.NewLogger()
	hlog.SetLogger(logger)
	hlog.SetLevel(conf.LogLevel())
	asyncWriter := &zapcore.BufferedWriteSyncer{
		WS: zapcore.AddSync(&lumberjack.Logger{
			Filename:   conf.GetConf().Hertz.LogFileName,
			MaxSize:    conf.GetConf().Hertz.LogMaxSize,
			MaxBackups: conf.GetConf().Hertz.LogMaxBackups,
			MaxAge:     conf.GetConf().Hertz.LogMaxAge,
		}),
		FlushInterval: time.Minute,
	}
	hlog.SetOutput(asyncWriter)
	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		asyncWriter.Sync()
	})

	// pprof
	if conf.GetConf().Hertz.EnablePprof {
		pprof.Register(h)
	}

	// gzip
	if conf.GetConf().Hertz.EnableGzip {
		h.Use(gzip.Gzip(gzip.DefaultCompression))
	}

	// access log
	if conf.GetConf().Hertz.EnableAccessLog {
		h.Use(accesslog.New())
	}

	// recovery
	h.Use(recovery.Recovery())

	// cores
	h.Use(cors.Default())

	// 注册鉴权中间件
	middleware.Register(h)
}

// 健康监测接口
func StartHealthCheckServer(addr string) {
	go func() {
		http.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusOK)
			w.Write([]byte("ok"))
		})
		if err := http.ListenAndServe(addr, nil); err != nil {
			log.Fatalf("health check server error: %v", err)
		}
	}()
}
