// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	auth "github.com/cloudwego/gomall/app/frontend/biz/router/auth"
	category "github.com/cloudwego/gomall/app/frontend/biz/router/category"
	home "github.com/cloudwego/gomall/app/frontend/biz/router/home"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	category.Register(r)

	auth.Register(r)

	home.Register(r)
}
